[2023-03-23 15:19:50,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:19:25.043237+00:00 [queued]>
[2023-03-23 15:19:50,286] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:19:25.043237+00:00 [queued]>
[2023-03-23 15:19:50,290] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:19:50,298] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-23 15:19:50,301] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:19:50,442] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack1> on 2023-03-23 15:19:25.043237+00:00
[2023-03-23 15:19:50,469] {standard_task_runner.py:52} INFO - Started process 12156 to run task
[2023-03-23 15:19:50,494] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack1', 'manual__2023-03-23T15:19:25.043237+00:00', '--job-id', '3041', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmp1zzzcgvk', '--error-file', '/tmp/tmpvt0xhcpf']
[2023-03-23 15:19:50,501] {standard_task_runner.py:80} INFO - Job 3041: Subtask attack1
[2023-03-23 15:19:50,816] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:19:25.043237+00:00 [running]> on host 6447f1dacd32
[2023-03-23 15:19:51,230] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack1
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T15:19:25.043237+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T15:19:25.043237+00:00
[2023-03-23 15:19:51,293] {python.py:173} INFO - Done. Returned value was: None
[2023-03-23 15:19:51,363] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=attack1, execution_date=20230323T151925, start_date=20230323T151950, end_date=20230323T151951
[2023-03-23 15:19:51,451] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-23 15:19:51,599] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
