[2023-04-27 09:09:28,732] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_ShapeShifter manual__2023-04-27T09:01:19.609297+00:00 [queued]>
[2023-04-27 09:09:28,980] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_ShapeShifter manual__2023-04-27T09:01:19.609297+00:00 [queued]>
[2023-04-27 09:09:29,001] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 09:09:29,009] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-27 09:09:29,019] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 09:09:29,328] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack_ShapeShifter> on 2023-04-27 09:01:19.609297+00:00
[2023-04-27 09:09:29,613] {standard_task_runner.py:52} INFO - Started process 2861 to run task
[2023-04-27 09:09:29,641] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack_ShapeShifter', 'manual__2023-04-27T09:01:19.609297+00:00', '--job-id', '6472', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpqg6hakq8', '--error-file', '/tmp/tmp521emkb8']
[2023-04-27 09:09:29,673] {standard_task_runner.py:80} INFO - Job 6472: Subtask attack_ShapeShifter
[2023-04-27 09:09:30,390] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack_ShapeShifter manual__2023-04-27T09:01:19.609297+00:00 [running]> on host e7e31d5a6603
[2023-04-27 09:09:31,007] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack_ShapeShifter
AIRFLOW_CTX_EXECUTION_DATE=2023-04-27T09:01:19.609297+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-27T09:01:19.609297+00:00
[2023-04-27 09:09:31,015] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-27 09:09:31,031] {client.py:777} INFO - Refreshing access_token
[2023-04-27 09:09:32,101] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-27 09:09:32,104] {client.py:777} INFO - Refreshing access_token
[2023-04-27 09:09:51,957] {pytorch.py:1198} INFO - Inferred 5 hidden layers on PyTorch classifier.
[2023-04-27 09:12:54,576] {attack_dag.py:642} INFO - Optimizing...
[2023-04-27 09:12:54,581] {logging_mixin.py:115} INFO - I am right here on <class 'art.attacks.evasion.shapeshifter.ShapeShifter'>
[2023-04-27 09:12:54,583] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack_dag.py", line 514, in attack_ShapeShifter
    model_acc, adversarial_examples  = attack(ShapeShifter)
  File "/opt/airflow/dags/attack_dag.py", line 643, in attack
    optimized_attack = optimize_evasion_attack(attack_obj,estimator,x_test,y_test)
  File "/opt/airflow/dags/attack_dag.py", line 616, in optimize_evasion_attack
    search_space = [v for k, v in attack_parameter_range[attack.__name__].items()]
KeyError: 'ShapeShifter'
[2023-04-27 09:12:54,608] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_attack_dag, task_id=attack_ShapeShifter, execution_date=20230427T090119, start_date=20230427T090928, end_date=20230427T091254
[2023-04-27 09:12:54,638] {standard_task_runner.py:97} ERROR - Failed to execute job 6472 for task attack_ShapeShifter ('ShapeShifter'; 2861)
[2023-04-27 09:12:54,692] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-27 09:12:54,880] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
