[2023-03-23 11:14:04,384] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-23T11:14:02.625158+00:00 [queued]>
[2023-03-23 11:14:04,391] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-23T11:14:02.625158+00:00 [queued]>
[2023-03-23 11:14:04,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 11:14:04,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-23 11:14:04,392] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 11:14:04,403] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-23 11:14:02.625158+00:00
[2023-03-23 11:14:04,407] {standard_task_runner.py:52} INFO - Started process 1291 to run task
[2023-03-23 11:14:04,410] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag2', 'attack', 'manual__2023-03-23T11:14:02.625158+00:00', '--job-id', '2614', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmpr_yq7qvq', '--error-file', '/tmp/tmppnl5q5n8']
[2023-03-23 11:14:04,411] {standard_task_runner.py:80} INFO - Job 2614: Subtask attack
[2023-03-23 11:14:04,456] {task_command.py:369} INFO - Running <TaskInstance: attack_dag2.attack manual__2023-03-23T11:14:02.625158+00:00 [running]> on host 6447f1dacd32
[2023-03-23 11:14:04,511] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag2
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T11:14:02.625158+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T11:14:02.625158+00:00
[2023-03-23 11:14:04,517] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-03-23 11:14:04,519] {client.py:777} INFO - Refreshing access_token
[2023-03-23 11:14:05,409] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-03-23 11:14:05,410] {client.py:777} INFO - Refreshing access_token
[2023-03-23 11:14:06,089] {python.py:173} INFO - Done. Returned value was: None
[2023-03-23 11:14:06,100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=attack_dag2, task_id=attack, execution_date=20230323T111402, start_date=20230323T111404, end_date=20230323T111406
[2023-03-23 11:14:06,152] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-23 11:14:06,185] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
