[2023-04-23 08:35:24,131] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:35:20.544164+00:00 [queued]>
[2023-04-23 08:35:24,154] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:35:20.544164+00:00 [queued]>
[2023-04-23 08:35:24,155] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 08:35:24,156] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-23 08:35:24,157] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 08:35:24,205] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): choose_attack> on 2023-04-23 08:35:20.544164+00:00
[2023-04-23 08:35:24,219] {standard_task_runner.py:52} INFO - Started process 2299 to run task
[2023-04-23 08:35:24,231] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'choose_attack', 'manual__2023-04-23T08:35:20.544164+00:00', '--job-id', '5972', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpumlm1fsn', '--error-file', '/tmp/tmp1v0t2o64']
[2023-04-23 08:35:24,233] {standard_task_runner.py:80} INFO - Job 5972: Subtask choose_attack
[2023-04-23 08:35:24,447] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:35:20.544164+00:00 [running]> on host a3dd7d962104
[2023-04-23 08:35:24,691] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=choose_attack
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T08:35:20.544164+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T08:35:20.544164+00:00
[2023-04-23 08:35:24,806] {python.py:173} INFO - Done. Returned value was: None
[2023-04-23 08:35:24,838] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=choose_attack, execution_date=20230423T083520, start_date=20230423T083524, end_date=20230423T083524
[2023-04-23 08:35:24,890] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-23 08:35:25,013] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
