[2023-03-23 15:00:38,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-03-23T15:00:34.488071+00:00 [queued]>
[2023-03-23 15:00:38,807] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-03-23T15:00:34.488071+00:00 [queued]>
[2023-03-23 15:00:38,809] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:00:38,811] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-23 15:00:38,815] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:00:38,926] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): choose_attack> on 2023-03-23 15:00:34.488071+00:00
[2023-03-23 15:00:38,947] {standard_task_runner.py:52} INFO - Started process 11056 to run task
[2023-03-23 15:00:38,977] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'choose_attack', 'manual__2023-03-23T15:00:34.488071+00:00', '--job-id', '2750', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmppnt3vxiu', '--error-file', '/tmp/tmpy487_q_2']
[2023-03-23 15:00:38,984] {standard_task_runner.py:80} INFO - Job 2750: Subtask choose_attack
[2023-03-23 15:00:39,297] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.choose_attack manual__2023-03-23T15:00:34.488071+00:00 [running]> on host 6447f1dacd32
[2023-03-23 15:00:39,890] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=choose_attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T15:00:34.488071+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T15:00:34.488071+00:00
[2023-03-23 15:00:40,128] {python.py:173} INFO - Done. Returned value was: None
[2023-03-23 15:00:40,215] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=choose_attack, execution_date=20230323T150034, start_date=20230323T150038, end_date=20230323T150040
[2023-03-23 15:00:40,320] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-23 15:00:40,660] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
