[2023-04-27 08:25:57,857] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.to_attack_ElasticNet scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-27 08:25:58,208] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.to_attack_ElasticNet scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-27 08:25:58,218] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 08:25:58,219] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-04-27 08:25:58,225] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 08:25:58,392] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): to_attack_ElasticNet> on 2023-04-23 00:00:00+00:00
[2023-04-27 08:25:58,474] {standard_task_runner.py:52} INFO - Started process 554 to run task
[2023-04-27 08:25:58,585] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'to_attack_ElasticNet', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '6328', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpresdj5rh', '--error-file', '/tmp/tmp02ouh32z']
[2023-04-27 08:25:58,604] {standard_task_runner.py:80} INFO - Job 6328: Subtask to_attack_ElasticNet
[2023-04-27 08:25:59,171] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.to_attack_ElasticNet scheduled__2023-04-23T00:00:00+00:00 [running]> on host e7e31d5a6603
[2023-04-27 08:26:00,367] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=to_attack_ElasticNet
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T00:00:00+00:00
[2023-04-27 08:26:00,423] {python.py:173} INFO - Done. Returned value was: default
[2023-04-27 08:26:00,425] {skipmixin.py:140} INFO - Following branch default
[2023-04-27 08:26:00,427] {skipmixin.py:175} INFO - Skipping tasks ['attack_ElasticNet']
[2023-04-27 08:26:00,789] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=to_attack_ElasticNet, execution_date=20230423T000000, start_date=20230427T082557, end_date=20230427T082600
[2023-04-27 08:26:00,928] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-27 08:26:01,994] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
