[2023-03-23 15:33:44,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:33:35.269730+00:00 [queued]>
[2023-03-23 15:33:44,488] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:33:35.269730+00:00 [queued]>
[2023-03-23 15:33:44,489] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:33:44,490] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-23 15:33:44,491] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:33:44,527] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack1> on 2023-03-23 15:33:35.269730+00:00
[2023-03-23 15:33:44,536] {standard_task_runner.py:52} INFO - Started process 12773 to run task
[2023-03-23 15:33:44,543] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack1', 'manual__2023-03-23T15:33:35.269730+00:00', '--job-id', '3277', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmp1rehi2ed', '--error-file', '/tmp/tmpycfbgru9']
[2023-03-23 15:33:44,546] {standard_task_runner.py:80} INFO - Job 3277: Subtask attack1
[2023-03-23 15:33:44,694] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack1 manual__2023-03-23T15:33:35.269730+00:00 [running]> on host 6447f1dacd32
[2023-03-23 15:33:44,937] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack1
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T15:33:35.269730+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T15:33:35.269730+00:00
[2023-03-23 15:33:44,981] {python.py:173} INFO - Done. Returned value was: None
[2023-03-23 15:33:45,053] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=attack1, execution_date=20230323T153335, start_date=20230323T153344, end_date=20230323T153345
[2023-03-23 15:33:45,121] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-23 15:33:45,234] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
