[2023-04-23 10:36:13,345] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T10:36:09.561696+00:00 [queued]>
[2023-04-23 10:36:13,365] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T10:36:09.561696+00:00 [queued]>
[2023-04-23 10:36:13,366] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 10:36:13,371] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-23 10:36:13,372] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 10:36:13,398] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): choose_attack> on 2023-04-23 10:36:09.561696+00:00
[2023-04-23 10:36:13,409] {standard_task_runner.py:52} INFO - Started process 3448 to run task
[2023-04-23 10:36:13,416] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'choose_attack', 'manual__2023-04-23T10:36:09.561696+00:00', '--job-id', '6186', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpghjxt3pi', '--error-file', '/tmp/tmp9wi0b1fc']
[2023-04-23 10:36:13,418] {standard_task_runner.py:80} INFO - Job 6186: Subtask choose_attack
[2023-04-23 10:36:13,527] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T10:36:09.561696+00:00 [running]> on host a3dd7d962104
[2023-04-23 10:36:13,678] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=choose_attack
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T10:36:09.561696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T10:36:09.561696+00:00
[2023-04-23 10:36:13,851] {python.py:173} INFO - Done. Returned value was: None
[2023-04-23 10:36:13,887] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=choose_attack, execution_date=20230423T103609, start_date=20230423T103613, end_date=20230423T103613
[2023-04-23 10:36:13,955] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-23 10:36:14,064] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
