[2023-04-18 08:08:00,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.metadata manual__2023-04-18T08:07:52.787849+00:00 [queued]>
[2023-04-18 08:08:00,494] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.metadata manual__2023-04-18T08:07:52.787849+00:00 [queued]>
[2023-04-18 08:08:00,495] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-18 08:08:00,496] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-18 08:08:00,496] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-18 08:08:00,507] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): metadata> on 2023-04-18 08:07:52.787849+00:00
[2023-04-18 08:08:00,513] {standard_task_runner.py:52} INFO - Started process 5829 to run task
[2023-04-18 08:08:00,516] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'metadata', 'manual__2023-04-18T08:07:52.787849+00:00', '--job-id', '5614', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmppe76byk_', '--error-file', '/tmp/tmpwmtxo_2f']
[2023-04-18 08:08:00,517] {standard_task_runner.py:80} INFO - Job 5614: Subtask metadata
[2023-04-18 08:08:00,566] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.metadata manual__2023-04-18T08:07:52.787849+00:00 [running]> on host a3dd7d962104
[2023-04-18 08:08:00,629] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=metadata
AIRFLOW_CTX_EXECUTION_DATE=2023-04-18T08:07:52.787849+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-18T08:07:52.787849+00:00
[2023-04-18 08:08:00,631] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-18 08:08:00,633] {client.py:777} INFO - Refreshing access_token
[2023-04-18 08:08:01,339] {python.py:173} INFO - Done. Returned value was: None
[2023-04-18 08:08:01,349] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=metadata, execution_date=20230418T080752, start_date=20230418T080800, end_date=20230418T080801
[2023-04-18 08:08:01,375] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-18 08:08:01,410] {local_task_job.py:273} INFO - 3 downstream tasks scheduled from follow-on schedule check
