[2023-03-16 11:55:04,662] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag.attack manual__2023-03-12T15:09:17.285355+00:00 [queued]>
[2023-03-16 11:55:04,753] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag.attack manual__2023-03-12T15:09:17.285355+00:00 [queued]>
[2023-03-16 11:55:04,754] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-16 11:55:04,756] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-03-16 11:55:04,757] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-16 11:55:04,904] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-12 15:09:17.285355+00:00
[2023-03-16 11:55:04,956] {standard_task_runner.py:52} INFO - Started process 675 to run task
[2023-03-16 11:55:05,045] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag', 'attack', 'manual__2023-03-12T15:09:17.285355+00:00', '--job-id', '973', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmp6nnt6zjz', '--error-file', '/tmp/tmp_8nq4h4a']
[2023-03-16 11:55:05,123] {standard_task_runner.py:80} INFO - Job 973: Subtask attack
[2023-03-16 11:55:05,527] {task_command.py:369} INFO - Running <TaskInstance: attack_dag.attack manual__2023-03-12T15:09:17.285355+00:00 [running]> on host 596adcca7378
[2023-03-16 11:55:05,920] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-12T15:09:17.285355+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-12T15:09:17.285355+00:00
[2023-03-16 11:55:05,922] {logging_mixin.py:115} INFO - attacking!
[2023-03-16 11:55:05,922] {python.py:173} INFO - Done. Returned value was: None
[2023-03-16 11:55:05,967] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=attack_dag, task_id=attack, execution_date=20230312T150917, start_date=20230316T115504, end_date=20230316T115505
[2023-03-16 11:55:06,073] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-16 11:55:06,382] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
