[2023-03-19 10:02:17,196] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.attack3 manual__2023-03-19T10:02:13.021226+00:00 [queued]>
[2023-03-19 10:02:17,209] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.attack3 manual__2023-03-19T10:02:13.021226+00:00 [queued]>
[2023-03-19 10:02:17,209] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-19 10:02:17,210] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-19 10:02:17,211] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-19 10:02:17,224] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack3> on 2023-03-19 10:02:13.021226+00:00
[2023-03-19 10:02:17,229] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2023-03-19 10:02:17,232] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'attack3', 'manual__2023-03-19T10:02:13.021226+00:00', '--job-id', '1548', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmp2ixf5vg6', '--error-file', '/tmp/tmpisty4e1r']
[2023-03-19 10:02:17,233] {standard_task_runner.py:80} INFO - Job 1548: Subtask attack3
[2023-03-19 10:02:17,287] {task_command.py:369} INFO - Running <TaskInstance: xcom_dag.attack3 manual__2023-03-19T10:02:13.021226+00:00 [running]> on host cff84a72f41c
[2023-03-19 10:02:17,352] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=attack3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T10:02:13.021226+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-19T10:02:13.021226+00:00
[2023-03-19 10:02:17,366] {python.py:173} INFO - Done. Returned value was: None
[2023-03-19 10:02:17,383] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=attack3, execution_date=20230319T100213, start_date=20230319T100217, end_date=20230319T100217
[2023-03-19 10:02:17,445] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-19 10:02:17,479] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
