[2023-04-23 08:19:44,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:19:40.670843+00:00 [queued]>
[2023-04-23 08:19:44,793] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:19:40.670843+00:00 [queued]>
[2023-04-23 08:19:44,794] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 08:19:44,795] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-23 08:19:44,795] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-23 08:19:44,830] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): choose_attack> on 2023-04-23 08:19:40.670843+00:00
[2023-04-23 08:19:44,844] {standard_task_runner.py:52} INFO - Started process 1539 to run task
[2023-04-23 08:19:44,848] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'choose_attack', 'manual__2023-04-23T08:19:40.670843+00:00', '--job-id', '5954', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpwy_q52mg', '--error-file', '/tmp/tmp1unfg12r']
[2023-04-23 08:19:44,850] {standard_task_runner.py:80} INFO - Job 5954: Subtask choose_attack
[2023-04-23 08:19:44,947] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.choose_attack manual__2023-04-23T08:19:40.670843+00:00 [running]> on host a3dd7d962104
[2023-04-23 08:19:45,102] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=choose_attack
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T08:19:40.670843+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T08:19:40.670843+00:00
[2023-04-23 08:19:45,218] {python.py:173} INFO - Done. Returned value was: None
[2023-04-23 08:19:45,246] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=choose_attack, execution_date=20230423T081940, start_date=20230423T081944, end_date=20230423T081945
[2023-04-23 08:19:45,313] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-23 08:19:45,424] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
